# .circleci/config.yml
version: 2.1
orbs:
  macos: circleci/macos@2.5.4

jobs:
  iOS:
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - run:
          name: Node Version
          command: |
            nvm install v20.19.0 && nvm alias default 20.19.0
      - run:
          name: Run iOS Test
          command: |
            nvm install v20.19.0 && nvm alias default 20.19.0
            node -v 
            npm ci
            npm run integration-ios

workflows:
  build:
    jobs:
      - iOS